### PR TITLE
feat: rework force and ignore

### PR DESCRIPTION
**Pull request by mbhall88**
### Added

- `--ignore` to ignore MD5 checksums

### Changed

- (**BREAKING**) the `--force` flag now overwrites existing files, but will check the MD5 checksums of the downloaded files. Previously, it would force download the file, but ignore the MD5 as well. See https://github.com/rpetit3/fastq-dl/issues/21#issuecomment-2190686184 for more details. Use the newly added `--ignore` flag to ignore MD5 checksums too.

This will need a major version bump as the `--force` functionality isn't backwards compatible.

Also added a bunch of unit tests and did a little bit of refactoring. The refactoring was more just moving functions into separate files as the code base grows this will make it less busy. I think more large-scale refactoring could be in order to have a `Downloader` class that seamlessly handles the SRA or ENA downloading etc. But one thing at a time.

### CODE REVIEW

**Comment by rpetit3** [comment]
looks great, thank you very much! I added some reminders for me on the changelog.

I wonder if in the future, adding separate commands `fastq-dl-ena` (or `ena-dl`) and `fastq-dl-sra` (or `sra-dl`) to limit downloads to respective databases might be worth it.

I'll think more about the unit tests as well.

**Comment by mbhall88** [comment]
I don't think subcommands are necessary. I think we can just refactor it to make downloading from different sources "seamless". Something like an AbstractClass that provides methods for downloading the fastq and then each provider has it's own implementation of that function. That also makes it future proof in case some other provider comes along or one of the current ones changes substantially.

**Comment by rpetit3** [comment]
Sounds good, let's put switching this over to Classes on the shelf for now.  I'll get some more refactoring done, then some time in the future we can revisit

**Comment by mbhall88** [comment]
Just a gentle nudge to see if we could get a release soon with this feature as I am about to start using it very heavily

**Pull request merged**
