### PR TITLE
Add fall back on SRA if ENA fails

### PR DESCRIPTION
**Pull request by mbhall88**
As the title suggests, this PR adds functionality that will try from SRA if ENA fails.

I formatted the code with black sorry, so the PR looks more complicated than it is.

Feel free to not take any of this either. I won't be offended.

## Added
- `-o` shorthand option for `--outdir`
- a flag `-F/--only-provider`, which supercedes `--sra_only`. I left `--sra_only` in there for backwards compatibility and added a deprecation notice in the help description for it.
- Conda environment file
- Dockerfile. Feel free to try out an image from my quay.io repo [here](https://quay.io/repository/mbhall88/fastq-dl?tab=tags).

## Changed
- Move everything into a `main` function to avoid [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing)
- Provider is now optional and defaults to `ena`. I've also made the option case insensitive, rather than listing the cased versions of the available providers
- If ENA download fails, try SRA
- Reduced a bunch of `execute` calls which were mostly operations easily dealt with by `pathlib.Path`
- Changed `md5sum` to use `hashlib.md5` instead of executing a subprocess call to `md5sum`
- Moved a bunch of `import` statements out of function bodies to the top of the file

## Removed
- Docstring at top of file as this is a mirror of argparse's help menu and creates needless maintenance

### CODE REVIEW

**Comment by rpetit3** [comment]
Awesome thank you very much @mbhall88 !

I've got to get a poster put together, but will get to this ASAP. Quick glance everything looked fine to me

Thanks again!

**Review by mbhall88 — COMMENTED** [review]
A very pedantic thought; maybe a minor version bump would be more suitable?

From [semver](https://semver.org/)

> MINOR version when you add functionality in a backwards compatible manner

**Comment by rpetit3** [comment]
Good call!

**Comment by mbhall88** [comment]
I also have a few other fixes incoming so maybe hold off merging

**Comment by mbhall88** [comment]
Okay, I've updated the original comment with a list of all of the stuff I have done. Again, I won't be offended if you don't want some/all of this. I just thought I'd suggest it as I use this project quite heavily and find these things to be quite useful.

Thanks for creating this tool!

**Comment by rpetit3** [comment]
@mbhall88 let me know when you think its all set.

**Comment by mbhall88** [comment]
I've successfully run it now on ~290 run accessions that wouldn't download successfully with v1.0.6 👍 So I reckon it's good to go.

**Comment by rpetit3** [comment]
Awesome! Just wanted to make sure you got all the changes in you'd like.

**Comment by rpetit3** [comment]
Thank you so much @mbhall88 I'm planning a release for Bactopia and going to try and sneak this in there as well!

**Comment by mbhall88** [comment]
Thank *you* for the SUPER helpful tool. I hate dealing with the SRA/ENA APIs so you've saved me a tonne of days dealing with that stuff.

**Pull request merged**
